source 'https://rubygems.org'


gem 'rails', '4.1.6'
gem 'pry'
gem 'rails-api'
gem 'acts_as_commentable'
gem 'acts-as-taggable-on', '~> 3.4'
gem 'spring', :group => :development
gem 'rack-cors', :require => 'rack/cors'

gem 'pg'

gem 'active_model_serializers','0.8.1'

# To use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano', :group => :development

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
